global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ['gateway:3000']

  - job_name: token
    static_configs:
      - targets: ['token:8080']

  - job_name: trust
    static_configs:
      - targets: ['trust:8080']

  - job_name: audit
    static_configs:
      - targets: ['audit:8080']
